### ISSUE TITLE
Any license?

### ISSUE THREAD

**Issue by akrzemi1** [pfultz2/Tick#16]
Is there any license tat applies to this library? It is listed in Boost Library Incubator. Do you intend to distribute it under Boost Software License 1.0?

**Comment by pfultz2** [comment]
It is boost licensed which is stated at the top of each header.

**Comment by akrzemi1** [comment]
Oh, ok. How about adding the contents in the root directory? (https://github.com/pfultz2/Tick/pull/17)
GitHub recognizes it as special file and will give a nice summary to potential users.
