### ISSUE TITLE
How to disable C<T>.f(T) for T void?

### ISSUE THREAD

**Issue by wiktortomczak** [pfultz2/Tick#21]
In a template class with template parameter `T`, I'd like to conditionally enable a non-template method taking a parameter of type `T` - enable if `T` is not `void`:

```c++
template <typename T>
class C {
public:
  void f(T t) { }    // enable for non-void T
  void f() { }       // enable for void T
};

int main() {
  C<int>().f(1);
  C<void>().f();
  return 0;
}
```

Compiling the above with `g++ -std=c++17 -Wall` gives 
`In instantiation of ‘class C<void>’: invalid parameter type ‘void’`

I tried `TICK_MEMBER_REQUIRES`, but I'm getting the same error

```c++
#include <type_traits>
#include "tick/requires.h"

template <typename T>
class C {
public:
  TICK_MEMBER_REQUIRES(!std::is_void_v<T>)
  void f(T t) { }

  TICK_MEMBER_REQUIRES(std::is_void_v<T>)
  void f() { }
};

int main() {
  C<int>().f(1);
  C<void>().f();
  return 0;
}
```

Is there any way I could disable the first `f` overload for `T = void` without changing `f` parameter type from `T` to some dummy template parameter type `T_`, as below?

```c++
template <typename T>
class C {
public:
  template <typename T_ = T, typename = std::enable_if_t<!std::is_void_v<T_>>>
  void f(T_ t) {}

  template <typename T_ = T, typename = std::enable_if_t<std::is_void_v<T_>>>
  void f() {}
};
```

Thanks for help.

**Comment by pfultz2** [comment]
The `T` is substitute when instantiating the class, so substitution failure for `f` won't prevent the function from being generated. The only other alternative I can think of is to have it fallback on empty `void_` type:

```cpp
struct void_ {};

template<class T>
using avoid = std::conditional_t<std::is_void<T>{}, void_, T>;

template <class T>
class C {
public:
  TICK_MEMBER_REQUIRES(!std::is_void<T>{})
  void f(avoid<T> t) { }

  TICK_MEMBER_REQUIRES(std::is_void<T>{})
  void f() { }
};
```

Which can work for some cases.

**Comment by wiktortomczak** [comment]
I like this solution, thanks for a quick response.
